apiVersion: v1
kind: Pod
metadata:
  name: java-web-service-pod
  labels:
    app: java-web-service
spec:
  nodeName: kind-cluster-worker
  containers:
    - name: java-web-service-container
      image: docker.io/nagabhushanamn/java-web-service:batch9
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: volume1
          mountPath: /app/log
    - name: log-reader-container
      image: alpine:latest
      command: ["sleep", "infinity"]   
      volumeMounts:
        - name: volume1
          mountPath: /app/log

  volumes:
    - name: volume1
      # emptyDir: {}
      # hostPath:
      #   path: /mnt/data
      #   type: DirectoryOrCreate
      persistentVolumeClaim:
        claimName: nfs-pvc-1
      
        
