
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""  
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.4
    path: "/npci/nfs/jws/log"