
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis

