apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: city
            operator: In
            values: ["mumbai","hyderabad"]
  containers:
  - name: nginx
    image: nginx
