receivers:
  otlp:
    protocols:
      http:

exporters:
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
