global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'greeting-service'
    metrics_path: '/actuator/prometheus'   # ✅ Correct path
    static_configs:
      - targets: ['host.docker.internal:8080']
rule_files:
  - "alert.rules.yml"
