
pipeline{
    agent any
    stages{
        stage("compile"){
         steps{
            sh "cd week3/dev-ops/transfer-service"
            sh "./mvnw compile"
         }  
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}