
pipeline{
    agent any
    stages{
        stage("Compile"){
         steps{
            dir("week3/dev-ops/transfer-service"){
                sh "./mvnw compile"
            }
         }  
        }
        stage("Test"){
         steps{
            dir("week3/dev-ops/transfer-service"){
                sh "./mvnw test"
            }
         }  
        }
        stage("Package"){
         steps{
            dir("week3/dev-ops/transfer-service"){
                sh "./mvnw package -DskipTests"
            }
         }  
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}